# Copyright (c) 2023. Schizoid
# All rights reserved.

[versions]
kotlin = "1.9.10"

minecraft = "1.20.2"
fabric_api = "0.90.4+1.20.2"
fabric_kl = "1.10.10+kotlin.1.9.10"
fabric_loader = "0.14.24"
fabric_mappings = "1.20.2+build.4"
fabric_loom = "1.4-SNAPSHOT"

lyzev_events = "v1.0.2"
lyzev_settings = "1.0.0"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_mappings = { module = "net.fabricmc:yarn", version.ref = "fabric_mappings" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
fabric_kl = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric_kl" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

lyzev_events = { module = "com.github.Lyzev:Events", version.ref = "lyzev_events" }
lyzev_settings = { module = "com.github.Lyzev:Settings", version.ref = "lyzev_settings" }

[bundles]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin_serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
fabric_loom = { id = "fabric-loom", version.ref = "fabric_loom" }


