# Copyright (c) 2023. Schizoid
# All rights reserved.

[versions]
kotlin = "1.9.20"

dokka = "1.9.10"

# https://fabricmc.net/develop/
minecraft = "1.20.2"
yarn_mappings = "1.20.2+build.4"
fabric_loader = "0.14.24"
fabric_api = "0.90.7+1.20.2"
# https://github.com/FabricMC/fabric-language-kotlin/releases
fabric_kl = "1.10.13+kotlin.1.9.20"
# https://github.com/FabricMC/fabric-loom/releases
fabric_loom = "1.4-SNAPSHOT"

lyzev_events = "v1.0.2"
lyzev_settings = "1.0.0"

reflections = "0.10.2"
imgui = "1.86.11"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn_mappings = { module = "net.fabricmc:yarn", version.ref = "yarn_mappings" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
fabric_kl = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric_kl" }

lyzev_events = { module = "com.github.Lyzev:Events", version.ref = "lyzev_events" }
lyzev_settings = { module = "com.github.Lyzev:Settings", version.ref = "lyzev_settings" }

reflections = { module = "org.reflections:reflections", version.ref = "reflections" }
imgui_binding = { module = "io.github.spair:imgui-java-binding", version.ref = "imgui" }
imgui_lwjgl3 = { module = "io.github.spair:imgui-java-lwjgl3", version.ref = "imgui" }
imgui_natives_windows = { module = "io.github.spair:imgui-java-natives-windows", version.ref = "imgui" }
imgui_natives_linux = { module = "io.github.spair:imgui-java-natives-linux", version.ref = "imgui" }
imgui_natives_macos = { module = "io.github.spair:imgui-java-natives-macos", version.ref = "imgui" }

[bundles]
fabric = ["fabric_api", "fabric_loader", "fabric_kl"]
imgui = ["imgui_binding", "imgui_lwjgl3", "imgui_natives_windows", "imgui_natives_linux", "imgui_natives_macos"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin_serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
fabric_loom = { id = "fabric-loom", version.ref = "fabric_loom" }
