name: "Release Nightly Build"

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      - name: Set Commit Hash
        id: commit_hash
        run: echo "::set-output name=commit_hash::$(git log --pretty=format:'%h' -n 1)"
      - name: Set Current Date and Time
        id: current_datetime
        run: echo "::set-output name=current_datetime::$(date +'%Y.%m.%d %H:%M')"
      - name: Build the project
        run: ./gradlew build
      - name: Create Release Assets
        run: |
          echo "Running shell script with version: ${{ github.event.inputs.version }}"
          mkdir release
          
          cp build/libs/*.jar release
          
          for asset in release/*; do
            md5sum $asset >> $asset.md5
            sha1sum $asset >> $asset.sha1
            sha256sum $asset >> $asset.sha256
            sha512sum $asset >> $asset.sha512
          done
          
          ls -l release
      - uses: marvinpinto/action-automatic-releases@latest
        name: Create Release
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: 'nightly+${{ steps.commit_hash.outputs.commit_hash }}'
          title: 'Nightly Build ${{ steps.current_datetime.outputs.current_datetime }}'
          files: |
            release/*
