name: "Release"

on:
  workflow_dispatch:
  push:
    branches:
      - 'v*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle
      - name: Read version from gradle.properties
        id: get_version
        run: echo "::set-output name=mod_version::$(grep -oP 'mod_version=\K.+' gradle.properties)"
      - name: Read archives_base_name from gradle.properties
        id: get_archives_base_name
        run: echo "::set-output name=archives_base_name::$(grep -oP 'archives_base_name=\K.+' gradle.properties)"
      - name: Read minecraft version from libs.versions.toml
        id: get_minecraft_version
        run: echo "::set-output name=minecraft_version::$(grep -oP 'minecraft = "\K[^"]+' gradle/libs.versions.toml)"
      - name: Build the project
        run: ./gradlew build
      - name: Create Release Assets
        run: |
          echo "Running shell script with version: ${{ steps.get_version.outputs.mod_version }}"
          echo "Using archives_base_name: ${{ steps.get_archives_base_name.outputs.archives_base_name }}"
          mkdir release
          
          cp build/libs/*.jar release
          
          for asset in release/*; do
            md5sum $asset >> $asset.md5
            sha1sum $asset >> $asset.sha1
            sha256sum $asset >> $asset.sha256
            sha512sum $asset >> $asset.sha512
          done
          
          ls -l release
      - uses: marvinpinto/action-automatic-releases@latest
        name: Create Release
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: 'v${{ steps.get_version.outputs.mod_version }}+${{ steps.get_minecraft_version.outputs.minecraft_version }}'
          prerelease: false
          title: '${{ steps.get_archives_base_name.outputs.archives_base_name }} ${{ steps.get_version.outputs.mod_version }}+${{ steps.get_minecraft_version.outputs.minecraft_version }}'
          files: |
            release/*
